AddonId: Yalgrin_WineBridgePlugin
Packages:
  - Version: 0.1.0
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2026-01-03
    PackageUrl: https://github.com/Yalgrin/playnite-wine-bridge-plugin/releases/download/0.1.0/Yalgrin_WineBridgePlugin_0_1_0.pext
    Changelog:
      - Initial release
      - Added Steam integration
      - Added custom action support
  - Version: 0.1.1
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2026-01-04
    PackageUrl: https://github.com/Yalgrin/playnite-wine-bridge-plugin/releases/download/0.1.1/Yalgrin_WineBridgePlugin_0_1_1.pext
    Changelog:
      - Fixed an error that occurred while starting Steam
      - Added custom Steam play actions
  - Version: 0.2.0
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2026-01-09
    PackageUrl: https://github.com/Yalgrin/playnite-wine-bridge-plugin/releases/download/0.2.0/Yalgrin_WineBridgePlugin_0_2_0.pext
    Changelog:
      - Heroic Games Launcher integration
      - Easier configuration - auto-detect, no more Wine paths
      - No longer needed to set permissions for the script manually
  - Version: 0.2.1
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2026-01-10
    PackageUrl: https://github.com/Yalgrin/playnite-wine-bridge-plugin/releases/download/0.2.1/Yalgrin_WineBridgePlugin_0_2_1.pext
    Changelog:
      - Added an option to redirect explorer.exe and protocol calls to Linux
      - Adding a Heroic play action now sets the game install location
  - Version: 0.3.0
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2026-01-15
    PackageUrl: https://github.com/Yalgrin/playnite-wine-bridge-plugin/releases/download/0.3.0/Yalgrin_WineBridgePlugin_0_3_0.pext
    Changelog:
      - Added Lutris integration for GOG, Amazon, Epic, EA App, Battle.net and Itch.io libraries
      - Added Lutris play actions
  - Version: 0.3.1
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2026-01-24
    PackageUrl: https://github.com/Yalgrin/playnite-wine-bridge-plugin/releases/download/0.3.1/Yalgrin_WineBridgePlugin_0_3_1.pext
    Changelog:
      - Fixed Open metadata folder button not opening in Linux when option for redirecting explorer.exe is enabled
      - Fixed tool throwing an error when defining it with wine-bridge:// prefix