AddonId: Yalgrin_WineBridgePlugin
Packages:
  - Version: 0.1.0
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2026-01-03
    PackageUrl: https://github.com/Yalgrin/playnite-wine-bridge-plugin/releases/download/0.1.0/Yalgrin_WineBridgePlugin_0_1_0.pext
    Changelog:
      - Initial release
      - Added Steam integration
      - Added custom action support